# Generated by Django 3.2.3 on 2021-06-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted at'),
        ),
    ]
