# Generated by Django 3.2.3 on 2021-06-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_customuser_deleted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['username'], name='profiles_cu_usernam_b2cfed_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['hash'], name='profiles_cu_hash_14ff45_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='profiles_cu_email_508cf9_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['gender'], name='profiles_cu_gender_5308d4_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['country', 'state'], name='profiles_cu_country_2aa96d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['created_at'], name='profiles_cu_created_678a5a_idx'),
        ),
    ]
